[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_CATALOG_URL = "https://catalog-production-04a7.up.railway.app"
  VITE_API_URL = "https://basket-production-02d1.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
